repositories:
  - name: parity
    url: https://paritytech.github.io/helm-charts/

helmDefaults:
  createNamespace: false
  waitForJobs: true
releases:
  - name: rococo-mythical-rpc
    namespace: rococo
    chart: parity/node
    version: 4.7.2
    values:
      - values-mythical2-rpc.yaml
      - node:
          flags:
            - "--bootnodes  /dns4/rococo-mythical-collator-alice-node-0/tcp/30334/p2p/12D3KooWPHGSf49X8DWgKy5gHvf1YSy2JokYehLhfxA6kbMht2jB"
 

