apiVersion: v1
data:
  index.html: |
    404
  nginx.conf: |
    user nginx;
    worker_processes  10;
    error_log /dev/stdout info;

    events {
      worker_connections 256;
    }

    http {
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      types_hash_max_size 2048;
      server_tokens off;

      server_names_hash_bucket_size 64;
      server_name_in_redirect off;

      access_log /dev/stdout;

      server {
        listen       80;
        server_name  _;
        location / {
          root   /var/www/html;
          index  index.html index.htm;
        }
        location /tellor/0 {
          allow 37.228.253.200;
          allow 35.232.202.47;
          proxy_pass http://localrococo-bootnode-0:9944;
          proxy_buffers 16 4k;
          proxy_buffer_size 2k;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          #proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;

        }
        location /tellor/1000  {
           allow 37.228.253.200;
           allow 35.232.202.47;
           proxy_buffers 16 4k;
           proxy_buffer_size 2k;
           proxy_http_version 1.1;
           proxy_set_header Upgrade $http_upgrade;
           proxy_set_header Connection "Upgrade";
           proxy_set_header Host $host;
           proxy_pass http://localrococo-statemint-alice-node-0:9944;
        }

        location /tellor/2000 {
          allow 37.228.253.200;
          allow 35.232.202.47;
          proxy_buffers 16 4k;
          proxy_buffer_size 2k;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://localrococo-moonbase-alice-node-0:9944/;
        }
        location /tellor/2000/rpc {
          allow 37.228.253.200;
          allow 35.232.202.47;
          proxy_buffers 16 4k;
          proxy_buffer_size 2k;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_pass http://localrococo-moonbase-alice-node-0:9933/;
        }
        location /tellor/3000 {
          proxy_pass http://localrococo-tellor-alice-node:9944/;
          proxy_buffers 16 4k;
          proxy_buffer_size 2k;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          allow 37.228.253.200;
          allow 35.232.202.47;
        }

  
      }
    }
kind: ConfigMap
metadata:
  name: nginx
